name: discover
description: "Konjic Discover"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.1+10

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  provider: ^6.1.2
  auto_size_text: ^3.0.0
  intl: any
  animate_do: ^3.3.4
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_displaymode: ^0.6.0
  video_player: ^2.9.2
  # flutter_native_splash: ^2.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  
    - assets/images/
    - assets/videos/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf


# flutter_native_splash:
#   android: false
#   ios: false
#   web: false

#   background_image: "assets/images/ikonica.png"

#   android_12:
#    color: "#d4e4ed"
#    image: "assets/images/ikonica.png"
#    branding: "assets/images/ikonica.png"

